### ISSUE TITLE
Add EddieHub As an Organisation

### ISSUE THREAD

**Issue by verma-kunal** [pranavbaburaj/pranavbaburaj#1]
# Description

I see that you are a part of **EddieHub Community**
I would definitely recommend to add that in your profile as well, to show support and your community experience as well.

Head over to the link and raise an issue here:  
https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.md&title=Please+invite+me+to+the+GitHub+Community+Organization

Also, don't forget to make your name public after creating an issue and being accepted 
here: https://github.com/EddieHubCommunity

**Comment by pranavbaburaj** [comment]
Sure, thanks

**Comment by verma-kunal** [comment]
Hey !! I think you have added EddieHub in the orgs !!
So, I'll close this issue now !!

**Comment by pranavbaburaj** [comment]
Thank you
